# Numpy
    1. How to install numpy:
        1. [cmd/terminal] pip install numpy
        2. [notebook] !pip install numpy
    2. Why arrays? 
    3. Array, Data types, Shapes
    4. numpy functions
        1. np.zeros
        2. np.empty
        3. linespace
        4. random
    5. Array dimension
    6. Indexing & Slicing & Axis
    7. Stacking
    8. Numpy arrays are mutable

## How to install numpy

In [ ]:
# not recommended
!pip install numpy

### Why arrays?
Because they are extremely fast :)

In [1]:
import numpy as np
one_d_array = np.linspace(0, 100, 10_000_000)
print(f"one_d_array: {one_d_array[:5]}")
print(f"one_d_array: {one_d_array.size}")

one_d_array: [0.0000000e+00 1.0000001e-05 2.0000002e-05 3.0000003e-05 4.0000004e-05]
one_d_array: 10000000


In [5]:
import math
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst

### Let's check how we can do the same task using lists, for, and numpy arrays

In [6]:
# lists
%timeit get_lst(one_d_array)

2.49 s ± 29.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
# numpy
%timeit np.sin(one_d_array)

84.3 ms ± 891 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
ratio = (2.48 * 1000) / 84.3
print(f"ratio: {ratio}")

ratio: 29.418742586002374


In [2]:
# import numpy (convention)
import numpy as np

## Arrays, Data types, Shapes
Arrays in numpy are ndarray or simply n-dimensional arrays.
Arrays are fixed-sized in memory containing data of the same type, such as integers or floating point values.

In [3]:
# a simple way to create an array
array = np.array((1, 2, 3, 4, 5))
print(f"array: {array}, with {array.dtype} data type, and {array.shape} shape")

array: [1 2 3 4 5], with int32 data type, and (5,) shape


In [4]:
# set dtype explicity
array = np.array([1, 2, 3.5, 4, 5], dtype=np.float64)
print(f"array: {array}, with {array.dtype} data type, and {array.shape} shape")

array: [1.  2.  3.5 4.  5. ], with float64 data type, and (5,) shape


In [5]:
# Basic Operators on Numpy arrays
array = np.array([1, 2, 3.5, 4, 5], dtype=np.float32)
print(f"ndim: {array.ndim}, shape: {array.shape}, size: {array.size} , dtype: {array.dtype}, sum: {array.sum()}, mean: {array.mean():.3f}, std: {array.std():.2f}")

ndim: 1, shape: (5,), size: 5 , dtype: float32, sum: 15.5, mean: 3.100, std: 1.43


In [6]:
# change an array's dtype
array = np.array([1, 2, 3.9, 4, 5], dtype=np.float64)
print(f"before dtype: {array.dtype}")
array = array.astype(np.int32)
print(f"after dtype: {array.dtype}")
print(f"array: {array}")

before dtype: float64
after dtype: int32
array: [1 2 3 4 5]


In [7]:
# nd-arrays
lst = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
nd_array = np.array(lst, dtype=np.float64)
print(f"ndim: {nd_array.ndim}, shape: {nd_array.shape}, size: {nd_array.size} , dtype: {nd_array.dtype}, sum: {nd_array.sum()}")

ndim: 2, shape: (2, 5), size: 10 , dtype: float64, sum: 55.0


In [8]:
# transpose
nd_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
transposed_nd_array = nd_array.T
print(f"nd_array:\n{nd_array},\nshape: {nd_array.shape}")
print(f"transposed_nd_array:\n{transposed_nd_array},\nshape: {transposed_nd_array.shape}")

nd_array:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]],
shape: (2, 5)
transposed_nd_array:
[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]],
shape: (5, 2)


In [9]:
# np.transpose
ones = np.ones((1, 2, 8))
print(f"ones:\n{ones}")
np.transpose(ones, (1, 0, 2)).shape

ones:
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


(2, 1, 8)

In [10]:
# lets reshape an array
nd_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
print("nd_array shape:", nd_array.shape)
reshaped_array = nd_array.reshape((5, 2))
print("reshaped_array:", reshaped_array)
print("reshaped_array shape:", reshaped_array.shape)

nd_array shape: (2, 5)
reshaped_array: [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]
reshaped_array shape: (5, 2)


In [11]:
# lets reshape an array
nd_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
print("nd_array shape:", nd_array.shape)
reshaped_array = nd_array.reshape((10, -1))
print("reshaped_array:", reshaped_array)
print("reshaped_array shape:", reshaped_array.shape)

nd_array shape: (2, 5)
reshaped_array: [[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]
reshaped_array shape: (10, 1)


## Numpy Functions

In [12]:
# creates an nd-array containing zeros
zeros_array = np.zeros(shape=(3, 6))
print(zeros_array)
print(f"ndim: {zeros_array.ndim}, shape: {zeros_array.shape}, size: {zeros_array.size} , dtype: {zeros_array.dtype}, sum: {zeros_array.sum()}")

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
ndim: 2, shape: (3, 6), size: 18 , dtype: float64, sum: 0.0


In [19]:
# creates an empty nd-array, numbers are almost zero
empty_array = np.empty((4, 4))
print(empty_array)
print(f"ndim: {empty_array.ndim}, shape: {empty_array.shape}, size: {empty_array.size} , dtype: {empty_array.dtype}, sum: {empty_array.sum()}")

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
ndim: 2, shape: (4, 4), size: 16 , dtype: float64, sum: 16.0


In [20]:
# Returns evenly spaced numbers over a specified interval.
interval = np.linspace(0, 10, 5)
print(f"interval: {interval}")

interval: [ 0.   2.5  5.   7.5 10. ]


In [21]:
# Creates an array of ones
ones_array = np.ones((3, 4))
print("ones_array:\n", ones_array)

ones_array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.random

In [23]:
# random function, uniform-distribution beween 0-1.0
np.random.random((2, 5))

array([[0.88427911, 0.08878478, 0.87512287, 0.6987637 , 0.54846565],
       [0.40355026, 0.49916046, 0.20892081, 0.16871504, 0.83368331]])

In [27]:
# random function, standard_normal mean=0, std=1
np.random.standard_normal((2, 4))

array([[ 1.34209227,  0.17667218,  0.82377537,  0.3304958 ],
       [-0.00251113,  0.87488694,  0.82419092,  1.82130143]])

In [33]:
# normal distribution
np.random.normal(loc=20, scale=1, size=(2, 3))

array([[19.16931085, 19.72890188, 20.90276502],
       [20.96993434, 19.04334153, 19.25959294]])

### dummy array

In [36]:
dummy_array = np.array([1, 2, 3, 4])
print(f"dummy_array:\n{dummy_array},\nshape: {dummy_array.shape}")
# why it's called dummy?
transposed_dummy_array = dummy_array.T
print(f"transposed_dummy_array:\n{transposed_dummy_array},\nshape: {transposed_dummy_array.shape}")
print(f"both arrays are the same: {np.all(transposed_dummy_array == dummy_array)}")

dummy_array:
[1 2 3 4],
shape: (4,)
transposed_dummy_array:
[1 2 3 4],
shape: (4,)
both arrays are the same: True


### Indexing & Slicing & Axis 

In [37]:
array = np.random.random((4, 5))
array

array([[0.45853074, 0.65631789, 0.17428689, 0.86468645, 0.7740036 ],
       [0.67117275, 0.87565634, 0.88341578, 0.22127502, 0.40411414],
       [0.4373681 , 0.06224675, 0.83311318, 0.85684873, 0.15754392],
       [0.82392886, 0.94515747, 0.83459254, 0.04470891, 0.85436195]])

In [38]:
# Accessing a value
array[1, 2]
# list -> lst[1][2]

0.8834157806647018

In [39]:
# Accessing a row
array[2, :]

array([0.4373681 , 0.06224675, 0.83311318, 0.85684873, 0.15754392])

In [40]:
# Accessing a column
array[:, 3]

array([0.86468645, 0.22127502, 0.85684873, 0.04470891])

In [ ]:
# nd-dimensional, this array is like an image (RGB)
array = np.random.random((4, 5, 3))
array

In [ ]:
# get the last dimension
array[:, :, 0] # getting first channel(R)

### Slicing

In [43]:
array = np.random.random((4, 5, 3))
sliced_array = array[:, ::2, :]
print(sliced_array)
print(sliced_array.shape)

[[[0.58736894 0.45953686 0.91541241]
  [0.85565047 0.77334659 0.67622007]
  [0.52843387 0.84957    0.01787371]]

 [[0.99615632 0.33199208 0.99947331]
  [0.32635999 0.24095858 0.80601194]
  [0.07883953 0.93453885 0.19689686]]

 [[0.41325026 0.14913819 0.20021304]
  [0.01681449 0.40717952 0.05316834]
  [0.5560527  0.34246529 0.55186074]]

 [[0.05988883 0.22453899 0.38683528]
  [0.24707148 0.88271523 0.73924548]
  [0.84671666 0.61951203 0.82028995]]]
(4, 3, 3)


In [ ]:
# negative and ...
# ... means take rest as they are
array = np.random.random((4, 5, 3))
sliced_array = array[1:-1, ...]
# sliced_array = array[1:-1, :, :]
print(sliced_array)
print(sliced_array.shape)

In [41]:
# dummy row
dummy_row = array[1, :]
print(f"dummy_row, {dummy_row.shape}:\n{dummy_row}")

dummy_row, (5,):
[0.67117275 0.87565634 0.88341578 0.22127502 0.40411414]


In [42]:
# Getting a row, but not in as a dummy array
not_dummy_row = array[1:2, :]
print(not_dummy_row)
print(not_dummy_row.shape)

[[0.67117275 0.87565634 0.88341578 0.22127502 0.40411414]]
(1, 5)


### Axis
sum can be replaced with any numpy function that operates on a bunch of numbers like, mean, std, and so on.

In [44]:
array = np.random.random((4, 5))
print(array)
print(f"sum column-wise/horrizontally:\n", array.sum(axis=1))

[[0.81376594 0.24465262 0.19802584 0.27754046 0.22733913]
 [0.00397167 0.08904099 0.60611583 0.59062541 0.9871143 ]
 [0.57515224 0.79842247 0.49724855 0.48596249 0.17532801]
 [0.94909911 0.98632835 0.40805477 0.24647546 0.06002443]]
sum column-wise/horrizontally:
 [1.761324   2.2768682  2.53211376 2.64998212]


In [45]:
print(f"sum row-wise/vertically:\n", array.sum(axis=0))

sum row-wise/vertically:
 [2.34198896 2.11844443 1.70944499 1.60060382 1.44980588]


In [48]:
# nd-dimensional, this array is like an image (RGB)
array = np.random.random((4, 5, 3))
print(array)
print(f"array shape:", array.shape)
channel_wised_mean = array.mean(axis=2)
print(f"sum channel-wise:\n", channel_wised_mean)
print(f"channel-wise shape:", channel_wised_mean.shape)

[[[7.06155918e-01 8.51445098e-01 4.47087748e-01]
  [1.31451489e-01 4.62897068e-01 3.83902138e-01]
  [3.50329109e-01 2.55325138e-01 9.37140538e-01]
  [9.38564785e-01 2.21243083e-01 1.74831036e-02]
  [3.25955634e-01 8.39474666e-01 4.34522318e-01]]

 [[8.41843580e-01 7.80712607e-01 1.14935183e-01]
  [6.76565731e-01 9.74314478e-01 6.64017510e-01]
  [8.19606005e-01 7.38285616e-01 7.59466198e-01]
  [4.99400675e-01 2.18749119e-01 8.85763405e-01]
  [6.78740578e-01 9.66918130e-01 3.08213623e-02]]

 [[3.19811007e-04 8.22802835e-01 8.90161672e-01]
  [4.82221764e-02 6.85505142e-02 8.06734604e-01]
  [5.78328970e-01 4.68798752e-01 3.54779271e-01]
  [6.44006093e-01 7.17881943e-01 4.64281461e-02]
  [2.47198380e-01 2.56239501e-01 9.95356823e-01]]

 [[1.16849108e-01 2.76562320e-01 4.86245038e-01]
  [9.54032488e-01 7.99546846e-01 4.70804927e-01]
  [6.02392187e-01 2.25415865e-01 6.97896621e-03]
  [1.14323599e-01 7.31964184e-01 9.38563390e-01]
  [5.07994072e-01 8.46212384e-02 2.18727370e-01]]]
array shape:

### Stacking
How to combine more two or more arrays

In [52]:
array_1 = np.random.random((2, 3))
array_2 = np.random.random((4, 3))
array_3 = np.random.random((1, 3))

In [53]:
# Stack arrays in sequence vertically (row wise).
vstack = np.vstack([array_1, array_2, array_3])
print(vstack)
print(f"vstack shape:", vstack.shape)

[[0.56478316 0.62752478 0.25224687]
 [0.46855996 0.08024286 0.959329  ]
 [0.67737988 0.38045628 0.11754645]
 [0.10047833 0.9325139  0.59627482]
 [0.22911021 0.94408991 0.49301922]
 [0.5229615  0.16933263 0.50609451]
 [0.95279645 0.51667222 0.86259499]]
vstack shape: (7, 3)


In [54]:
array_1 = np.random.random((4, 5))
array_2 = np.random.random((4, 3))

In [55]:
# Stack arrays in sequence horizontally (column wise)
hstack = np.hstack([array_1, array_2])
print(hstack)
print(f"hstack shape:", hstack.shape)

[[0.06065347 0.0169426  0.00681024 0.25790187 0.70266436 0.15249116
  0.38598716 0.44631734]
 [0.19270385 0.42038138 0.85496352 0.02575514 0.55220714 0.12545528
  0.95003621 0.19058124]
 [0.01060189 0.8078461  0.82829623 0.78176449 0.42051277 0.87120892
  0.00901367 0.82571925]
 [0.94455056 0.71978091 0.1797401  0.57914218 0.72870392 0.51434491
  0.69326203 0.76732728]]
hstack shape: (4, 8)


In [62]:
array_1 = np.random.random((4, 5))
array_2 = np.random.random((4, 5))

In [66]:
# Join a sequence of arrays along a new axis
stack = np.stack([array_1, array_2], axis=0)
print(stack)
print(f"stack shape:", stack.shape)

[[[0.73867706 0.60183287 0.54784959 0.16911158 0.58553714]
  [0.86991473 0.25411314 0.60013525 0.86225335 0.37962161]
  [0.12855986 0.14324087 0.28404052 0.35581008 0.78898084]
  [0.67751507 0.63236418 0.94849558 0.38402615 0.99686076]]

 [[0.28616814 0.01481299 0.11012833 0.87549117 0.51425181]
  [0.60335915 0.47066277 0.69526548 0.58708435 0.17259027]
  [0.39305673 0.62366149 0.26308753 0.34252176 0.8630318 ]
  [0.06575171 0.95273524 0.77829881 0.67605888 0.50295602]]]
stack shape: (2, 4, 5)


## Numpy arrays are mutable

In [68]:
array_1 = np.array([1, 2, 3])
array_2 = array_1
array_2[0] = 10
print(f"array_1:\n{array_1}")
print(f"array_2:\n{array_2}")

array_1:
[10  2  3]
array_2:
[10  2  3]


In [69]:
# how to prevent changes that occur due to mutability of numpy arrays
array_1 = np.array([1, 2, 3])
array_2 = array_1.copy()
array_2[0] = 10
print(f"array_1:\n{array_1}")
print(f"array_2:\n{array_2}")

[1 2 3]
[10  2  3]


*:)*