# Numpy
    1. How to install numpy:
        1. [cmd/terminal] pip install numpy
        2. [notebook] !pip install numpy
    2. Why arrays? 
    3. Array, Data types, Shapes
    4. numpy functions
        1. np.zeros
        2. np.empty
        3. linespace
        4. random
    5. Array dimension
    6. Indexing & Slicing & Axis
    7. Stacking
    8. Numpy arrays are mutable

## How to install numpy

In [ ]:
# not recommended
!pip install numpy

### Why arrays?
Because they are extremely fast :)

In [ ]:
import numpy as np
one_d_array = np.linspace(0, 100, 10_000_000)
print(f"one_d_array: {one_d_array[:5]}")
print(f"one_d_array: {one_d_array.size}")

In [ ]:
import math
def get_lst(x):
    lst = []
    for i in x:
        lst.append(math.sin(i))
    return lst

### Let's check how we can do the same task using lists, for, and numpy arrays

In [ ]:
# lists
%timeit get_lst(one_d_array)

In [ ]:
# numpy
%timeit np.sin(one_d_array)

In [ ]:
ratio = (2.48 * 1000) / 84.3
print(f"ratio: {ratio}")

In [ ]:
# import numpy (convention)
import numpy as np

## Arrays, Data types, Shapes
Arrays in numpy are ndarray or simply n-dimensional arrays.
Arrays are fixed-sized in memory containing data of the same type, such as integers or floating point values.

In [ ]:
# a simple way to create an array
array = np.array((1, 2, 3, 4, 5))
print(f"array: {array}, with {array.dtype} data type, and {array.shape} shape")

In [ ]:
# set dtype explicity
array = np.array([1, 2, 3.5, 4, 5], dtype=np.float64)
print(f"array: {array}, with {array.dtype} data type, and {array.shape} shape")

In [ ]:
# Basic Operators on Numpy arrays
array = np.array([1, 2, 3.5, 4, 5], dtype=np.float32)
print(f"ndim: {array.ndim}, shape: {array.shape}, size: {array.size} , dtype: {array.dtype}, sum: {array.sum()}, mean: {array.mean():.3f}, std: {array.std():.2f}")

In [ ]:
# change an array's dtype
array = np.array([1, 2, 3.9, 4, 5], dtype=np.float64)
print(f"before dtype: {array.dtype}")
array = array.astype(np.int32)
print(f"after dtype: {array.dtype}")
print(f"array: {array}")

In [ ]:
# nd-arrays
lst = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
nd_array = np.array(lst, dtype=np.float64)
print(f"ndim: {nd_array.ndim}, shape: {nd_array.shape}, size: {nd_array.size} , dtype: {nd_array.dtype}, sum: {nd_array.sum()}")

In [ ]:
# transpose
nd_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
transposed_nd_array = nd_array.T
print(f"nd_array:\n{nd_array},\nshape: {nd_array.shape}")
print(f"transposed_nd_array:\n{transposed_nd_array},\nshape: {transposed_nd_array.shape}")

In [ ]:
# np.transpose
ones = np.ones((1, 2, 8))
print(f"ones:\n{ones}")
np.transpose(ones, (1, 0, 2)).shape

In [ ]:
# lets reshape an array
nd_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
print("nd_array shape:", nd_array.shape)
reshaped_array = nd_array.reshape((5, 2))
print("reshaped_array:", reshaped_array)
print("reshaped_array shape:", reshaped_array.shape)

In [ ]:
# lets reshape an array
nd_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
print("nd_array shape:", nd_array.shape)
reshaped_array = nd_array.reshape((10, -1))
print("reshaped_array:", reshaped_array)
print("reshaped_array shape:", reshaped_array.shape)

## Numpy Functions

In [ ]:
# creates an nd-array containing zeros
zeros_array = np.zeros(shape=(3, 6))
print(zeros_array)
print(f"ndim: {zeros_array.ndim}, shape: {zeros_array.shape}, size: {zeros_array.size} , dtype: {zeros_array.dtype}, sum: {zeros_array.sum()}")

In [ ]:
# creates an empty nd-array, numbers are almost zero
empty_array = np.empty((4, 4))
print(empty_array)
print(f"ndim: {empty_array.ndim}, shape: {empty_array.shape}, size: {empty_array.size} , dtype: {empty_array.dtype}, sum: {empty_array.sum()}")

In [ ]:
# Returns evenly spaced numbers over a specified interval.
interval = np.linspace(0, 10, 5)
print(f"interval: {interval}")

In [ ]:
# Creates an array of ones
ones_array = np.ones((3, 4))
print("ones_array:\n", ones_array)

### np.random

In [ ]:
# random function, uniform-distribution beween 0-1.0
np.random.random((2, 5))

In [23]:
# random function, standard_normal mean=0, std=1
np.random.standard_normal((2, 4))

array([[ 1.31815155, -0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023,  0.33743765]])

In [ ]:
# normal distribution
np.random.normal(loc=20, scale=1, size=(2, 3))

In [35]:
# seed
np.random.seed(seed=1234)
print("first:\n", np.random.standard_normal((2, 4)))
print("second:\n", np.random.standard_normal((2, 4)))

first:
 [[ 0.47143516 -1.19097569  1.43270697 -0.3126519 ]
 [-0.72058873  0.88716294  0.85958841 -0.6365235 ]]
second:
 [[ 1.56963721e-02 -2.24268495e+00  1.15003572e+00  9.91946022e-01]
 [ 9.53324128e-01 -2.02125482e+00 -3.34077366e-01  2.11836468e-03]]


In [36]:
# seed
np.random.seed(seed=1234)
print("first:\n", np.random.standard_normal((2, 4)))
print("second:\n", np.random.standard_normal((2, 4)))

first:
 [[ 0.47143516 -1.19097569  1.43270697 -0.3126519 ]
 [-0.72058873  0.88716294  0.85958841 -0.6365235 ]]
second:
 [[ 1.56963721e-02 -2.24268495e+00  1.15003572e+00  9.91946022e-01]
 [ 9.53324128e-01 -2.02125482e+00 -3.34077366e-01  2.11836468e-03]]


### dummy array

In [ ]:
dummy_array = np.array([1, 2, 3, 4])
print(f"dummy_array:\n{dummy_array},\nshape: {dummy_array.shape}")
# why it's called dummy?
transposed_dummy_array = dummy_array.T
print(f"transposed_dummy_array:\n{transposed_dummy_array},\nshape: {transposed_dummy_array.shape}")
print(f"both arrays are the same: {np.all(transposed_dummy_array == dummy_array)}")

### Indexing & Slicing & Axis 

In [ ]:
array = np.random.random((4, 5))
array

In [ ]:
# Accessing a value
array[1, 2]
# list -> lst[1][2]

In [ ]:
# Accessing a row
array[2, :]

In [ ]:
# Accessing a column
array[:, 3]

In [ ]:
# nd-dimensional, this array is like an image (RGB)
array = np.random.random((4, 5, 3))
array

In [ ]:
# get the last dimension
array[:, :, 0] # getting first channel(R)

### Slicing

In [ ]:
array = np.random.random((4, 5, 3))
sliced_array = array[:, ::2, :]
print(sliced_array)
print(sliced_array.shape)

In [ ]:
# negative and ...
# ... means take rest as they are
array = np.random.random((4, 5, 3))
sliced_array = array[1:-1, ...]
# sliced_array = array[1:-1, :, :]
print(sliced_array)
print(sliced_array.shape)

In [ ]:
# dummy row
dummy_row = array[1, :]
print(f"dummy_row, {dummy_row.shape}:\n{dummy_row}")

In [ ]:
# Getting a row, but not in as a dummy array
not_dummy_row = array[1:2, :]
print(not_dummy_row)
print(not_dummy_row.shape)

### Axis
sum can be replaced with any numpy function that operates on a bunch of numbers like, mean, std, and so on.

In [ ]:
array = np.random.random((4, 5))
print(array)
print(f"sum column-wise/horrizontally:\n", array.sum(axis=1))

In [ ]:
print(f"sum row-wise/vertically:\n", array.sum(axis=0))

In [ ]:
# nd-dimensional, this array is like an image (RGB)
array = np.random.random((4, 5, 3))
print(array)
print(f"array shape:", array.shape)
channel_wised_mean = array.mean(axis=2)
print(f"sum channel-wise:\n", channel_wised_mean)
print(f"channel-wise shape:", channel_wised_mean.shape)

In [5]:
# keepdims
import numpy as np
array = np.random.random((4, 5))
dummy_array = array.sum(axis=1)
print(f"dummy_array:\n{dummy_array},\nshape: {dummy_array.shape}")
two_d_array = array.sum(axis=1, keepdims=True)
print(f"two_d_array:\n{two_d_array},\nshape: {two_d_array.shape}")

dummy_array:
[1.91798929 2.4959994  2.53252953 3.03267557],
shape: (4,)
two_d_array:
[[1.91798929]
 [2.4959994 ]
 [2.53252953]
 [3.03267557]],
shape: (4, 1)


In [10]:
# expand_dims
array = np.random.random((256, 256, 3))
print(f"array: {array.shape}")

# expand_dims
expanded_array = np.expand_dims(array, axis=0)
print(f"expanded_array: {expanded_array.shape}")

# expand_dims
expanded_array = array.reshape(1, *array.shape)
# expanded_array = array.reshape(1, 256, 256, 3)
print(f"expanded_array: {expanded_array.shape}")


array: (256, 256, 3)
expanded_array: (1, 256, 256, 3)
expanded_array: (1, 256, 256, 3)


In [9]:
# squeeze_dim
squeezed_array = np.squeeze(expanded_array, axis=0) 
print(f"squeezed_array: {squeezed_array.shape}")

squeezed_array: (256, 256, 3)


In [11]:
# squeeze does not work on dimensions whose size are not equal to one
print(f"array: {array.shape}")
squeezed_array_2 = np.squeeze(array, axis=2)
print(f"squeezed_array_2: {squeezed_array_2.shape}")

array: (256, 256, 3)


ValueError: cannot select an axis to squeeze out which has size not equal to one

### Stacking
How to combine more two or more arrays

In [ ]:
array_1 = np.random.random((2, 3))
array_2 = np.random.random((4, 3))
array_3 = np.random.random((1, 3))

In [ ]:
# Stack arrays in sequence vertically (row wise).
vstack = np.vstack([array_1, array_2, array_3])
print(vstack)
print(f"vstack shape:", vstack.shape)

In [ ]:
array_1 = np.random.random((4, 5))
array_2 = np.random.random((4, 3))

In [ ]:
# Stack arrays in sequence horizontally (column wise)
hstack = np.hstack([array_1, array_2])
print(hstack)
print(f"hstack shape:", hstack.shape)

In [ ]:
array_1 = np.random.random((4, 5))
array_2 = np.random.random((4, 5))

In [ ]:
# Join a sequence of arrays along a new axis
stack = np.stack([array_1, array_2], axis=0)
print(stack)
print(f"stack shape:", stack.shape)

## Numpy arrays are mutable

In [ ]:
array_1 = np.array([1, 2, 3])
array_2 = array_1
array_2[0] = 10
print(f"array_1:\n{array_1}")
print(f"array_2:\n{array_2}")

In [ ]:
# how to prevent changes that occur due to mutability of numpy arrays
array_1 = np.array([1, 2, 3])
array_2 = array_1.copy()
array_2[0] = 10
print(f"array_1:\n{array_1}")
print(f"array_2:\n{array_2}")

*:)*