# Numpy - part 02
    1. boolean masks
    2. Mathematical Operations
    3. Broadcasting
    4. np.where & Unicode array
    5. Datetime
    6. Save & Load    

In [ ]:
# import numpy
import numpy as np

## Boolean masks

In [ ]:
array = np.array([1, 2, 3, 10, 6, -2])
array

In [ ]:
# get a group of indices
array[[2, 2, 0, -1]]

In [ ]:
# create a boolean mask for numbers which are larger than a pre-defined number
a_number = 5
boolean_mask = array > 5
print("boolean mask:", boolean_mask)

In [ ]:
# get values using boolean mask
print(f"values which are larger than {a_number}:", array[boolean_mask])

In [ ]:
print(f"values which are larger than {a_number}:", array[array > 5])

### Mathematical Operations

In [ ]:
array = np.random.random((2, 3))
cos_array = np.cos(array)
sine_array = np.sin(array)
print(f'cosine_array: {cos_array.shape}')
print(f'sine_array: {sine_array.shape}')

In [ ]:
# Add
array_1 = np.random.randint(0, 10, (4, 5))
array_2 = np.ones_like(array_1)
print(f"array_1:\n{array_1}")
print(f"array_2:\n{array_2}")
print(f"array_1 + array_2 =\n{array_1 + array_2}")

In [ ]:
# matrix multiplication
array_1 = np.random.random((4, 5))
array_2 = np.ones_like(array_1).T
print(f"array_1: {array_1.shape}\n{array_1}")
print(f"array_2: {array_2.shape}\n{array_2}")
matrix_multiplication = np.dot(array_1, array_2)
# or
# matrix_multiplication = np.matmul(array_1, array_2)
print(f"array_1 * array_2 =\n{matrix_multiplication}")
print(f"shape: {matrix_multiplication.shape}")

In [ ]:
# elementwise multiplication
array_1 = np.random.random((4, 5))
array_2 = np.ones_like(array_1) * 2 # broadcasting, we'll check it in the next section
print(f"array_1: {array_1.shape}\n{array_1}")
print(f"array_2: {array_2.shape}\n{array_2}")
element_wise_multiplication = np.multiply(array_1,  array_2)
# element_wise_multiplication = array_1 * array_2
print(f"array_1 * array_2 =\n{element_wise_multiplication}")
print(f"shape: {element_wise_multiplication.shape}")

In [ ]:
# task -> ((A'PA)^-1)(A'PL)
A = np.array([[1, 2],[3, 5],[7, 6]])
P = np.diag([5, 5, 5])
L = np.array([7, 3, 2]).reshape((3, 1))

# answer ...
# If you don't know some of the funtions asked in the task, Google them...
# To be honest, at the time of writing thses comments I coudn't remember how to do inversion in numpy :D

### Broadcasting

In [ ]:
array_1 = np.ones((6, 5))
array_1

In [ ]:
# element-wise add
array_2 = np.random.random((6, 5))
print(f"array_1: {array_1.shape}")
print(f"array_2: {array_2.shape}")
print(f"array_1 + array_2 =\n{array_1 + array_2}")

In [43]:
# how broadcasting works
scalar = 5
print(f"array_1: {array_1.shape}")
print(f"scalar: {scalar}")
print(f"array_1 + scalar =\n{array_1 + scalar}")

array_1: (6, 5)
scalar: 5
array_1 + scalar =
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [47]:
# how broadcasting works
array_2 = np.random.random((1,))
print(f"array_1: {array_1.shape}")
print(f"array_2: {array_2.shape}")
print(f"array_1 * array_2 =\n{array_1 * array_2}")

array_1: (6, 5)
array_2: (1,)
array_1 * array_2 =
[[0.62449269 0.62449269 0.62449269 0.62449269 0.62449269]
 [0.62449269 0.62449269 0.62449269 0.62449269 0.62449269]
 [0.62449269 0.62449269 0.62449269 0.62449269 0.62449269]
 [0.62449269 0.62449269 0.62449269 0.62449269 0.62449269]
 [0.62449269 0.62449269 0.62449269 0.62449269 0.62449269]
 [0.62449269 0.62449269 0.62449269 0.62449269 0.62449269]]


In [48]:
# how broadcasting works
array_2 = np.random.random((6, 1))
print(f"array_1: {array_1.shape}")
print(f"array_2: {array_2.shape}")
print(f"array_1 * array_2 =\n{array_1 * array_2}")

array_1: (6, 5)
array_2: (6, 1)
array_1 * array_2 =
[[0.72164371 0.72164371 0.72164371 0.72164371 0.72164371]
 [0.47127346 0.47127346 0.47127346 0.47127346 0.47127346]
 [0.21963461 0.21963461 0.21963461 0.21963461 0.21963461]
 [0.07488933 0.07488933 0.07488933 0.07488933 0.07488933]
 [0.26312471 0.26312471 0.26312471 0.26312471 0.26312471]
 [0.47606599 0.47606599 0.47606599 0.47606599 0.47606599]]


In [51]:
# how broadcasting does not work!
array_2 = np.random.random((2, 5))
print(f"array_1: {array_1.shape}")
print(f"array_2: {array_2.shape}")
print(f"array_1 * array_2 =\n{array_1 * array_2}")

array_1: (6, 5)
array_2: (2, 5)


ValueError: operands could not be broadcast together with shapes (6,5) (2,5) 

In [73]:
# repeat
array = np.array([[1, 2, 3, 4, 5, 6]]).reshape(6, 1)
print(f"array:\n{array}\nshape:{array.shape}")


repeated_array = np.repeat(array, 5, axis=1)
print(f"repeated_array:\n{repeated_array}\nshape:{repeated_array.shape}")

array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
shape:(6, 1)
repeated_array:
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]
 [6 6 6 6 6]]
shape:(6, 5)


## Where

In [52]:
unicode_array = np.array([[1, 2, 3, 'foo'],
                          [2, 3, 4, 'bar'],
                          [5, 6, 7, 'hello'],
                          [8, 9, 1, 'bar'],
                         ])
print(f"unicode_array:\n{unicode_array}, dtype: {unicode_array.dtype}, shape: {unicode_array.shape}")

unicode_array:
[['1' '2' '3' 'foo']
 ['2' '3' '4' 'bar']
 ['5' '6' '7' 'hello']
 ['8' '9' '1' 'bar']], dtype: <U11, shape: (4, 4)


In [56]:
rows , cols = np.where(unicode_array == 'bar')
print(f"rows: {rows}")
print(f"cols: {cols}")

rows: [1 3]
cols: [3 3]


In [58]:
array = np.array([[1, 2, 3],
                  [2, 3, 4],
                  [5, 6, 7],
                  [8, 9, 1],
                ])
rows , cols = np.where(array > 2)
print(f"rows: {rows}")
print(f"cols: {cols}")

rows: [0 1 1 2 2 2 3 3]
cols: [2 1 2 0 1 2 0 1]


## DateTime

In [59]:
# year
date = np.datetime64('2022')
print(f"date: {date}")

date: 2022


In [60]:
# month
date = np.datetime64('2022-08')
print(f"date: {date}")

date: 2022-08


In [61]:
# day
date = np.datetime64('2022-08-06')
print(f"date: {date}")

date: 2022-08-06


In [62]:
# datetime
date_time = np.datetime64('2022-08-06 20:30:00')
print(f"date_time: {date_time}")

date_time: 2022-08-06T20:30:00


In [63]:
# comparison
np.datetime64('2022-01-01') < np.datetime64('2022-04-03')

True

In [64]:
# subtraction
np.datetime64('2022-04-03') - np.datetime64('2022-01-01')

numpy.timedelta64(92,'D')

In [65]:
# time delta
np.datetime64('2022-08-06 20:30:00') + np.timedelta64(5, 'h')

numpy.datetime64('2022-08-07T01:30:00')

In [67]:
# date time range
date_time_range = np.arange(np.datetime64('2022-02-01'), np.datetime64('2022-03-01'))
date_time_range

array(['2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
       '2022-02-05', '2022-02-06', '2022-02-07', '2022-02-08',
       '2022-02-09', '2022-02-10', '2022-02-11', '2022-02-12',
       '2022-02-13', '2022-02-14', '2022-02-15', '2022-02-16',
       '2022-02-17', '2022-02-18', '2022-02-19', '2022-02-20',
       '2022-02-21', '2022-02-22', '2022-02-23', '2022-02-24',
       '2022-02-25', '2022-02-26', '2022-02-27', '2022-02-28'],
      dtype='datetime64[D]')

## Save & Load

In [76]:
array = np.random.randint(0, high=10, size=(5, 2))
print(f"array:\n{array}")
np.save('array.npy', array)

array:
[[6 7]
 [3 5]
 [1 3]
 [1 8]
 [0 9]]


In [77]:
loaded_array = np.load('array.npy')
loaded_array

array([[6, 7],
       [3, 5],
       [1, 3],
       [1, 8],
       [0, 9]])

In [78]:
print(f"Are both arrays the same: {np.all(loaded_array == array)}")

Are both arrays the same: True


*:)*